### ISSUE TITLE
Создать класс Response

### ISSUE THREAD

**Issue by maxkusnetsov** [ilb/pycgilib#5]
Отвечает за отправку различных видов ответов: статуса с текстом, ошибки, документа
[Документация](https://tools.ietf.org/html/rfc3875#section-6)

**Comment by Stew404** [comment]
https://github.com/Stew404/Stew-Who-Is/commit/b549ce245d97f9d13350b2b12cc00cb53a8bba89 - все задания.

**Comment by maxkusnetsov** [comment]
> [Stew404/Stew-Who-Is@b549ce2](https://github.com/Stew404/Stew-Who-Is/commit/b549ce245d97f9d13350b2b12cc00cb53a8bba89) - все задания.

Привет! Можешь сообщить свою почту (или что-нибудь другое) для связи? Хотелось бы обсудить решение, но тут это будет долго.

**Comment by Stew404** [comment]
> > [Stew404/Stew-Who-Is@b549ce2](https://github.com/Stew404/Stew-Who-Is/commit/b549ce245d97f9d13350b2b12cc00cb53a8bba89) - все задания.
> 
> Привет! Можешь сообщить свою почту (или что-нибудь другое) для связи? Хотелось бы обсудить решение, но тут это будет долго.

artembotov@mail.ru

**Comment by maxkusnetsov** [comment]
https://github.com/ilb/pycgilib/commit/1683abc6a313d0d5a15958dfc38d5106e2f7a392
